# Generated by Django 4.2.20 on 2026-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX – Ugandan Shilling'), ('USD', 'USD – US Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('KES', 'KES – Kenyan Shilling'), ('TZS', 'TZS – Tanzanian Shilling'), ('RWF', 'RWF – Rwandan Franc'), ('ETB', 'ETB – Ethiopian Birr'), ('ZAR', 'ZAR – South African Rand'), ('NGN', 'NGN – Nigerian Naira'), ('AED', 'AED – UAE Dirham'), ('INR', 'INR – Indian Rupee'), ('CNY', 'CNY – Chinese Yuan'), ('CAD', 'CAD – Canadian Dollar'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc')], default='UGX', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX – Ugandan Shilling'), ('USD', 'USD – US Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('KES', 'KES – Kenyan Shilling'), ('TZS', 'TZS – Tanzanian Shilling'), ('RWF', 'RWF – Rwandan Franc'), ('ETB', 'ETB – Ethiopian Birr'), ('ZAR', 'ZAR – South African Rand'), ('NGN', 'NGN – Nigerian Naira'), ('AED', 'AED – UAE Dirham'), ('INR', 'INR – Indian Rupee'), ('CNY', 'CNY – Chinese Yuan'), ('CAD', 'CAD – Canadian Dollar'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc')], default='UGX', max_length=3),
        ),
    ]
