# Generated by Django 6.0.4 on 2026-04-20 06:07

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_currency_alter_payment_currency'),
        ('rentals', '0011_add_payment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(choices=[('UGX', 'UGX – Ugandan Shilling'), ('USD', 'USD – US Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('KES', 'KES – Kenyan Shilling'), ('TZS', 'TZS – Tanzanian Shilling'), ('RWF', 'RWF – Rwandan Franc'), ('ETB', 'ETB – Ethiopian Birr'), ('ZAR', 'ZAR – South African Rand'), ('NGN', 'NGN – Nigerian Naira'), ('AED', 'AED – UAE Dirham'), ('INR', 'INR – Indian Rupee'), ('CNY', 'CNY – Chinese Yuan'), ('CAD', 'CAD – Canadian Dollar'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc')], default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Licenses'), ('marketing', 'Marketing & Advertising'), ('salaries', 'Staff Salaries'), ('supplies', 'Office Supplies'), ('legal', 'Legal & Professional'), ('cleaning', 'Cleaning Services'), ('security', 'Security'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.budget')),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('expense_type', models.CharField(choices=[('operational', 'Operational'), ('capital', 'Capital Expenditure'), ('emergency', 'Emergency'), ('planned', 'Planned')], default='operational', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('UGX', 'UGX – Ugandan Shilling'), ('USD', 'USD – US Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('KES', 'KES – Kenyan Shilling'), ('TZS', 'TZS – Tanzanian Shilling'), ('RWF', 'RWF – Rwandan Franc'), ('ETB', 'ETB – Ethiopian Birr'), ('ZAR', 'ZAR – South African Rand'), ('NGN', 'NGN – Nigerian Naira'), ('AED', 'AED – UAE Dirham'), ('INR', 'INR – Indian Rupee'), ('CNY', 'CNY – Chinese Yuan'), ('CAD', 'CAD – Canadian Dollar'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc')], default='UGX', max_length=3)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='billing.budgetitem')),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rentals.property')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rentals.rental')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
