# Generated by Django 4.2.20 on 2026-04-11 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/owner/'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_units',
            field=models.IntegerField(default=1, help_text='Number of rentable units in this property', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='property',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/property/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/rental/'),
        ),
    ]
