# Generated by Django 4.2.20 on 2026-04-12 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


def copy_owners_to_tenants(apps, schema_editor):
    """Copy Owner records used as tenants in Rentals into the new Tenant table,
    preserving the same UUID so the FK still resolves."""
    Owner = apps.get_model('rentals', 'Owner')
    Tenant = apps.get_model('rentals', 'Tenant')
    Rental = apps.get_model('rentals', 'Rental')

    # Get distinct owner IDs referenced as tenants
    tenant_owner_ids = Rental.objects.values_list('tenant_id', flat=True).distinct()
    for owner in Owner.objects.filter(pk__in=tenant_owner_ids):
        Tenant.objects.create(
            id=owner.id,  # keep same PK so existing FK values stay valid
            tenant_type=owner.owner_type,
            company_name=owner.company_name,
            registration_number=owner.registration_number,
            tax_id=owner.tax_id,
            first_name=owner.first_name,
            last_name=owner.last_name,
            national_id=owner.national_id,
            email=owner.email,
            phone=owner.phone,
            address=owner.address,
            city=owner.city,
            country=owner.country,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_owner_qr_code_image_property_number_of_units_and_more'),
    ]

    operations = [
        # Step 1: Create the Tenant table
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/tenant/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # Step 2: Copy Owner data into Tenant for existing rentals
        migrations.RunPython(copy_owners_to_tenants, migrations.RunPython.noop),
        # Step 3: Point the FK to the new Tenant table
        migrations.AlterField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.tenant'),
        ),
    ]
