# Generated by Django 4.2.20 on 2026-04-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_tenant_alter_rental_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.tenant'),
        ),
    ]
