# Generated by Django 4.2.20 on 2026-04-12 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='rental',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='number_of_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_type', models.CharField(choices=[('lease', 'Lease Agreement'), ('tenancy', 'Tenancy Agreement'), ('sublease', 'Sublease Agreement'), ('room_rental', 'Room Rental Agreement'), ('commercial', 'Commercial Lease'), ('other', 'Other Agreement')], default='lease', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('agreement_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_paid', models.BooleanField(default=False)),
                ('terms', models.TextField(blank=True, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='rental_agreements/')),
                ('tenant_signature', models.ImageField(blank=True, null=True, upload_to='signatures/tenant/')),
                ('landlord_signature', models.ImageField(blank=True, null=True, upload_to='signatures/landlord/')),
                ('witness_signature', models.ImageField(blank=True, null=True, upload_to='signatures/witness/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='rentals.rental')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
