# Generated by Django 4.2.20 on 2026-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_property_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
