# Generated by Django 4.2.20 on 2026-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_make_end_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
