# Generated by Django 4.2.20 on 2026-04-12 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
