# Generated by Django 4.2.20 on 2026-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_property_currency_alter_rental_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
