# Generated by Django 4.2.20 on 2026-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_add_rental_name_and_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('weekly', 'Weekly'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
    ]
