# Generated by Django 4.2.20 on 2026-04-12 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('landlord', 'Landlord'), ('seeker', 'Room Seeker')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='marketplace/avatars/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('en_suite', 'En-suite Room'), ('studio', 'Studio'), ('whole_property', 'Whole Property')], default='double', max_length=20)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('house', 'House'), ('studio', 'Studio Flat'), ('bungalow', 'Bungalow'), ('shared_house', 'Shared House')], default='flat', max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bills_included', models.BooleanField(default=False)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furnished', models.BooleanField(default=True)),
                ('available_from', models.DateField()),
                ('min_term', models.CharField(choices=[('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months'), ('12m', '12 months'), ('any', 'No minimum')], default='1m', max_length=5)),
                ('current_occupants', models.PositiveIntegerField(default=0)),
                ('max_occupants', models.PositiveIntegerField(default=2)),
                ('smokers_ok', models.BooleanField(default=False)),
                ('pets_ok', models.BooleanField(default=False)),
                ('couples_ok', models.BooleanField(default=False)),
                ('dss_ok', models.BooleanField(default=False)),
                ('students_ok', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('has_dishwasher', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('let', 'Let Agreed'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.marketplaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='marketplace/listings/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.roomlisting')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sender_phone', models.CharField(blank=True, max_length=30)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('replied', 'Replied')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='marketplace.roomlisting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='marketplace.roomlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
