# Generated by Django 4.2.20 on 2026-04-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='has_disabled_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='has_living_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_gender',
            field=models.CharField(blank=True, choices=[('any', 'Any gender'), ('male', 'Male only'), ('female', 'Female only'), ('mixed', 'Mixed')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current household max age'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current household min age'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_occupation',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('professional', 'Professional'), ('student', 'Student'), ('mixed', 'Mixed')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_pets',
            field=models.BooleanField(default=False, verbose_name='Current occupants have pets'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_smoker',
            field=models.BooleanField(default=False, verbose_name='Current occupants smoke'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='hh_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='max_preferred_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='max_term',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months'), ('12m', '12 months')], default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='min_preferred_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='preferred_occupation',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('professional', 'Professional'), ('student', 'Student'), ('mixed', 'Mixed')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='references_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='min_term',
            field=models.CharField(choices=[('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months'), ('9m', '9 months'), ('12m', '12 months'), ('any', 'No minimum')], default='1m', max_length=5),
        ),
    ]
