# Generated by Django 6.0.4 on 2026-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_roomlisting_has_balcony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('KES', 'KES'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='UGX', max_length=3),
        ),
    ]
